[project]
name = "beeminder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beeminder-client>=0.1.5",
    "mcp[cli]>=1.3.0",
]
